import Layout from "../../../components/Layout";

export default function Home() {
  return (
    <Layout>
      <section className="max-w-2xl space-y-4">
        <p className="text-sm font-medium uppercase tracking-[0.2em] text-slate-500">
          Home
        </p>
        <h1 className="text-4xl font-bold">Editorial Control Center</h1>
        <p className="text-slate-600">
          Project generated by Specwright. Run the stories to build it out.
        </p>
      </section>
    </Layout>
  );
}
