import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import Home from "../app/page";
import payloadConfig from "../payload.config";

describe("bootstrap smoke", () => {

  it("loads the payload config", async () => {
    const config = await payloadConfig;

    expect(config).toBeDefined();
    expect(config).toHaveProperty("db");
    expect(config).toHaveProperty("secret");
  });

  it("home page smoke render includes the project title", () => {
  const html = renderToStaticMarkup(React.createElement(Home));

  expect(html).toContain("Editorial E2E Test");
  expect(html).toContain("Project generated by Specwright");
  });

  it("home page module exports a renderable component", () => {
    expect(typeof Home).toBe("function");
  });
});
